version: '3'

services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${API_PORT-8000}:${API_PORT-8000}"
    volumes:
      - .:/code
    command: uvicorn app.main:app --host ${API_HOST} --port ${API_PORT} --reload
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:6.2.5
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres